### ISSUE TITLE
v2 branch: regex: Missing characters (Windows)

### ISSUE THREAD

**Issue by Suisse00** [knyzorg/pluralsight-scraper#13]
TLDR: If somebody with Windows try to use it you will need to add such characters: :?*  (colon, question mark, star)

(I personally encounter the colon)

**Comment by vezaynk** [comment]
Filtered out here: https://github.com/knyzorg/pluralsight-scraper/blob/8388d58bfdb760d55f50e60ed852fbe063546ea4/index.js#L43
