### ISSUE TITLE
Scraper is not finding correct url for courses

### ISSUE THREAD

**Issue by javajohnHub** [knyzorg/pluralsight-scraper#2]
This is the console.log I used on line 54 to look at the module data. As you can see the titles are correct but almost every link is for table-of-contents.
Mac OS

Logging in...
{ courses: 
   [ { name: 'Course Overview',
       url: 'https://app.pluralsight.com/player?course=angular-2-getting-started&author=deborah-kurata&name=angular-2-getting-started-m0&clip=0&mode=live' },
     { name: 'Introduction',
       url: 'https://app.pluralsight.com/library/courses/angular-2-getting-started/table-of-contents' },
     { name: 'Anatomy of an Angular 2 Application ',
       url: 'https://app.pluralsight.com/library/courses/angular-2-getting-started/table-of-contents' },
     { name: 'Get the Most from This Course',
       url: 'https://app.pluralsight.com/library/courses/angular-2-getting-started/table-of-contents' },
     { name: 'Sample Application',
       url: 'https://app.pluralsight.com/library/courses/angular-2-getting-started/table-of-contents' },
     { name: 'Course Outline',
       url: 'https://app.pluralsight.com/library/courses/angular-2-getting-started/table-of-contents' },
     { name: 'Introduction',
       url: 'https://app.pluralsight.com/library/courses/angular-2-getting-started/table-of-contents' },
     { name: 'Selecting a Language',
       url: 'https://app.pluralsight.com/library/courses/angular-2-getting-started/table-of-contents' },
     { name: 'Selecting an Editor',
       url: 'https://app.pluralsight.com/library/courses/angular-2-getting-started/table-of-contents' },
     { name: 'Setting up Our Environment',
       url: 'https://app.pluralsight.com/library/courses/angular-2-getting-started/table-of-contents' },
     { name: 'Setting up an Angular 2 Application',
       url: 'https://app.pluralsight.com/library/courses/angular-2-getting-started/table-of-contents' },
     { name: 'Running an Angular 2 Application',
       url: 'https://app.pluralsight.com/library/courses/angular-2-getting-started/table-of-contents' },
     { name: 'About Modules',
       url: 'https://app.pluralsight.com/library/courses/angular-2-getting-started/table-of-contents' },
     { name: 'Loading Modules and Hosting our Application',
       url: 'https://app.pluralsight.com/library/courses/angular-2-getting-started/table-of-contents' },
     { name: 'Summary',
       url: 'https://app.pluralsight.com/library/courses/angular-2-getting-started/table-of-contents' },
     { name: 'Introduction',
       url: 'https://app.pluralsight.com/library/courses/angular-2-getting-started/table-of-contents' },
     { name: 'What Is a Component?',
       url: 'https://app.pluralsight.com/library/courses/angular-2-getting-started/table-of-contents' },
     { name: 'Creating the Component Class',
       url: 'https://app.pluralsight.com/library/courses/angular-2-getting-started/table-of-contents' },
     { name: 'Defining the Metadata with a Decorator',
       url: 'https://app.pluralsight.com/library/courses/angular-2-getting-started/table-of-contents' },
     { name: 'Importing What We Need',
       url: 'https://app.pluralsight.com/library/courses/angular-2-getting-started/table-of-contents' },
     { name: 'Demo: Creating the App Component',
       url: 'https://app.pluralsight.com/library/courses/angular-2-getting-started/table-of-contents' },
     { name: 'Bootstrapping the App Component',
       url: 'https://app.pluralsight.com/library/courses/angular-2-getting-started/table-of-contents' },
     { name: 'Demo: Bootstrapping the App Component',
       url: 'https://app.pluralsight.com/library/courses/angular-2-getting-started/table-of-contents' },
     { name: 'Checklists and Summary',
       url: 'https://app.pluralsight.com/library/courses/angular-2-getting-started/table-of-contents' },
     { name: 'Introduction',
       url: 'https://app.pluralsight.com/library/courses/angular-2-getting-started/table-of-contents' },
     { name: 'Building a Template',
       url: 'https://app.pluralsight.com/library/courses/angular-2-getting-started/table-of-contents' },
     { name: 'Building the Component',
       url: 'https://app.pluralsight.com/library/courses/angular-2-getting-started/table-of-contents' },
     { name: 'Using a Component as a Directive',
       url: 'https://app.pluralsight.com/library/courses/angular-2-getting-started/table-of-contents' },
     { name: 'Binding with Interpolation',
       url: 'https://app.pluralsight.com/library/courses/angular-2-getting-started/table-of-contents' },
     { name: 'Adding Logic with Directives: ngIf',
       url: 'https://app.pluralsight.com/library/courses/angular-2-getting-started/table-of-contents' },
     { name: 'Adding Logic with Directives: ngFor',
       url: 'https://app.pluralsight.com/library/courses/angular-2-getting-started/table-of-contents' },
     { name: 'Checklists and Summary',
       url: 'https://app.pluralsight.com/library/courses/angular-2-getting-started/table-of-contents' },
     { name: 'Introduction',
       url: 'https://app.pluralsight.com/library/courses/angular-2-getting-started/table-of-contents' },
     { name: 'Property Binding',
       url: 'https://app.pluralsight.com/library/courses/angular-2-getting-started/table-of-contents' },
     { name: 'Handling Events with Event Binding',
       url: 'https://app.pluralsight.com/library/courses/angular-2-getting-started/table-of-contents' },
     { name: 'Handling Input with Two-way Binding',
       url: 'https://app.pluralsight.com/library/courses/angular-2-getting-started/table-of-contents' },
     { name: 'Transforming Data with Pipes',
       url: 'https://app.pluralsight.com/library/courses/angular-2-getting-started/table-of-contents' },
     { name: 'Checklists and Summary',
       url: 'https://app.pluralsight.com/library/courses/angular-2-getting-started/table-of-contents' },
     { name: 'Introduction',
       url: 'https://app.pluralsight.com/library/courses/angular-2-getting-started/table-of-contents' },
     { name: 'Defining Interfaces',
       url: 'https://app.pluralsight.com/library/courses/angular-2-getting-started/table-of-contents' },
     { name: 'Encapsulating Component Styles',
       url: 'https://app.pluralsight.com/library/courses/angular-2-getting-started/table-of-contents' },
     { name: 'Using Lifecycle Hooks',
       url: 'https://app.pluralsight.com/library/courses/angular-2-getting-started/table-of-contents' },
     { name: 'Building Custom Pipes',
       url: 'https://app.pluralsight.com/library/courses/angular-2-getting-started/table-of-contents' },
     { name: 'Checklists and Summary',
       url: 'https://app.pluralsight.com/library/courses/angular-2-getting-started/table-of-contents' },
     { name: 'Introduction',
       url: 'https://app.pluralsight.com/library/courses/angular-2-getting-started/table-of-contents' },
     { name: 'Building a Nested Component',
       url: 'https://app.pluralsight.com/library/courses/angular-2-getting-started/table-of-contents' },
     { name: 'Using a Nested Component',
       url: 'https://app.pluralsight.com/library/courses/angular-2-getting-started/table-of-contents' },
     { name: 'Passing Data to a Nested Component Using @Input',
       url: 'https://app.pluralsight.com/library/courses/angular-2-getting-started/table-of-contents' },
     { name: 'Passing Data from a Component Using @Output',
       url: 'https://app.pluralsight.com/library/courses/angular-2-getting-started/table-of-contents' },
     { name: 'Checklists and Summary',
       url: 'https://app.pluralsight.com/library/courses/angular-2-getting-started/table-of-contents' },
     { name: 'Introduction',
       url: 'https://app.pluralsight.com/library/courses/angular-2-getting-started/table-of-contents' },
     { name: 'How Does It Work?',
       url: 'https://app.pluralsight.com/library/courses/angular-2-getting-started/table-of-contents' },
     { name: 'Building a Service',
       url: 'https://app.pluralsight.com/library/courses/angular-2-getting-started/table-of-contents' },
     { name: 'Registering the Service',
       url: 'https://app.pluralsight.com/library/courses/angular-2-getting-started/table-of-contents' },
     { name: 'Injecting the Service',
       url: 'https://app.pluralsight.com/library/courses/angular-2-getting-started/table-of-contents' },
     { name: 'Checklists and Summary',
       url: 'https://app.pluralsight.com/library/courses/angular-2-getting-started/table-of-contents' },
     { name: 'Introduction',
       url: 'https://app.pluralsight.com/library/courses/angular-2-getting-started/table-of-contents' },
     { name: 'Observables and Reactive Extensions',
       url: 'https://app.pluralsight.com/library/courses/angular-2-getting-started/table-of-contents' },
     { name: 'Setting Up',
       url: 'https://app.pluralsight.com/library/courses/angular-2-getting-started/table-of-contents' },
     { name: 'Sending an Http Request',
       url: 'https://app.pluralsight.com/library/courses/angular-2-getting-started/table-of-contents' },
     { name: 'Subscribing to an Observable',
       url: 'https://app.pluralsight.com/library/courses/angular-2-getting-started/table-of-contents' },
     { name: 'Checklists and Summary',
       url: 'https://app.pluralsight.com/library/courses/angular-2-getting-started/table-of-contents' },
     { name: 'Introduction',
       url: 'https://app.pluralsight.com/library/courses/angular-2-getting-started/table-of-contents' },
     { name: 'Setting Up',
       url: 'https://app.pluralsight.com/library/courses/angular-2-getting-started/table-of-contents' },
     { name: 'Configuring Routes',
       url: 'https://app.pluralsight.com/library/courses/angular-2-getting-started/table-of-contents' },
     { name: 'Tying Routes to Actions',
       url: 'https://app.pluralsight.com/library/courses/angular-2-getting-started/table-of-contents' },
     { name: 'Placing the Views',
       url: 'https://app.pluralsight.com/library/courses/angular-2-getting-started/table-of-contents' },
     { name: 'Passing Parameters to a Route',
       url: 'https://app.pluralsight.com/library/courses/angular-2-getting-started/table-of-contents' },
     { name: 'Activating a Route with Code',
       url: 'https://app.pluralsight.com/library/courses/angular-2-getting-started/table-of-contents' },
     { name: 'Checklists and Summary',
       url: 'https://app.pluralsight.com/library/courses/angular-2-getting-started/table-of-contents' },
     { name: 'Introduction',
       url: 'https://app.pluralsight.com/library/courses/angular-2-getting-started/table-of-contents' },
     { name: 'TypeScript Configuration File (tsconfig.json)',
       url: 'https://app.pluralsight.com/library/courses/angular-2-getting-started/table-of-contents' },
     { name: 'npm Package File (package.json) and TypeScript Definitions File (typings.json)',
       url: 'https://app.pluralsight.com/library/courses/angular-2-getting-started/table-of-contents' },
     { name: 'index.html File Libraries',
       url: 'https://app.pluralsight.com/library/courses/angular-2-getting-started/table-of-contents' },
     { name: 'Summary',
       url: 'https://app.pluralsight.com/library/courses/angular-2-getting-started/table-of-contents' },
     { name: 'Introduction',
       url: 'https://app.pluralsight.com/library/courses/angular-2-getting-started/table-of-contents' },
     { name: 'Recapping Our Journey',
       url: 'https://app.pluralsight.com/library/courses/angular-2-getting-started/table-of-contents' },
     { name: 'Learning More',
       url: 'https://app.pluralsight.com/library/courses/angular-2-getting-started/table-of-contents' },
     { name: 'What Is Angular? (Revisited)',
       url: 'https://app.pluralsight.com/library/courses/angular-2-getting-started/table-of-contents' },
     { name: 'Closing',
       url: 'https://app.pluralsight.com/library/courses/angular-2-getting-started/table-of-contents' } ],
  title: 'Angular 2: Getting Started | Pluralsight' }
Logged in!

**Comment by vezaynk** [comment]
This is strange. What are you inputing for target url?

**Comment by javajohnHub** [comment]
https://app.pluralsight.com/library/courses/angular-2-getting-started/table-of-contents

**Comment by vezaynk** [comment]
Works for me..

**Comment by javajohnHub** [comment]
Strange.

**Comment by vezaynk** [comment]
Your subscription expired. Closing!
