### ISSUE TITLE
Is there any way to download a specific range of videos ? 

### ISSUE THREAD

**Issue by Aryangh1379** [knyzorg/pluralsight-scraper#20]
Hi, imagine I downloaded half of videos today, and tomorrow i want to download the others, is there any way to do this ? 

Thanks

**Comment by theSuiGenerisAakash** [comment]
Why not raise a PR for it?

**Comment by vezaynk** [comment]
The way the previous version of it handled it was by verifying for the presence of the file before attempting to download the file. This is no longer feasible as the name comes from the API, which is the main bottleneck.

Nonetheless, we can use the prefixes of the files instead and skip them that way.

This to say that I don't think there is much point in specifying a range of videos. We should however support the ability to "resume" downloads.

**Comment by vezaynk** [comment]
Going to close this in favor of #21

**Comment by Aryangh1379** [comment]
> Why not raise a PR for it?

what is a PR ?

**Comment by vezaynk** [comment]
> 
> 
> > Why not raise a PR for it?
> 
> what is a PR ?

Pull Request
