### ISSUE TITLE
Can i download one file in a video set

### ISSUE THREAD

**Issue by coeur85** [knyzorg/pluralsight-scraper#27]
i'm trying to alter the index.js file to skip a number of video files and start download from index 40 for example. 

how can i implement that ?

**Comment by vezaynk** [comment]
Duplicate of #21 

I have written the basics of implementing a fix here: https://github.com/knyzorg/pluralsight-scraper/issues/21#issuecomment-614769187

**Comment by nilachandan** [comment]
> [https://github.com/knyzorg/pluralsight-scraper/issues](https://github.com/knyzorg/pluralsight-scraper/issues/21#issuecomment-614769187)

This Url is broken. I'm not being able to browse the Url.
