### ISSUE TITLE
The two last videos are not downloaded of a course

### ISSUE THREAD

**Issue by bonttimo** [knyzorg/pluralsight-scraper#28]
I have noticed that the two last videos of a course are not downloaded. It retrieves the video data but does not download it.

**Comment by vezaynk** [comment]
Which videos?

**Comment by bonttimo** [comment]
Always the two last videos from each course you download

**Comment by Brakerciti** [comment]
it shows me an npm error saying 
npm ERR! missing script: login

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Sam\AppData\Roaming\npm-cache\_logs\2020-04-30T17_37_05_078Z-debug.log
how can I fix this?

**Comment by vezaynk** [comment]
@Brakerciti You're in the wrong directory. This has nothing to do with the posted issue.
