### ISSUE TITLE
brings an error when I type in npm run login

### ISSUE THREAD

**Issue by Brakerciti** [knyzorg/pluralsight-scraper#29]
npm ERR! missing script: login

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Sam\AppData\Roaming\npm-cache\_logs\2020-04-30T18_09_50_653Z-debug.log

What should I do ?

**Comment by evo-home-task** [comment]
You should be inside `pluralsight-scraper` directory

**Comment by vezaynk** [comment]
Duplicate of #23
