### ISSUE TITLE
Cannot read property 'focus' of null`

### ISSUE THREAD

**Issue by invalidtruck** [knyzorg/pluralsight-scraper#3]
`>npm start

> pluralsight-scraper@1.0.0 start C:\proyectos\nodejs\pluralsight-scraper
> node index.js

This program was written for EDUCATION and PERSONAL USE ONLY
Please be respectful of the original authors' intellectual property

This scraper is open source and licensed under GPLv2 on Github
https://github.com/knyzorg/pluralsight-scraper

Logging in...
(node:16788) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Cannot read property 'focus' of null`

**Comment by vezaynk** [comment]
Thank you for opening this issue. It made me realize that I fucked up real bad and inevitably published my pluralsight password.

I will now need to focus on securing all my shit.

I will get to this later.

**Comment by vezaynk** [comment]
I ended up never getting to it. My pluralsight subscription also expired.

Whoops. Project will be now basically abandoned.

**Comment by kaloyanxoxo** [comment]
Hey @knyzorg ! I tried to use your script, but it just shows :
-------------------------------------------------------------
> node index.js

This program was written for EDUCATION and PERSONAL USE ONLY
Please be respectful of the original authors' intellectual property

This scraper is open source and licensed under GPLv2 on Github
https://github.com/knyzorg/pluralsight-scraper

Logging in...
-------------------------------------------------------------

And it ends

**Comment by Hassan1Hr** [comment]
Logging in...
goto: `url` must be a non-empty string

**Comment by UMUTBAYGUT** [comment]
Logging in...
goto: url must be a non-empty string

Same

**Comment by vezaynk** [comment]
This a new issue. I suspect that pluralsight changed something on their end. You're free to try to make a patch for this. You're equally free to sponsor me with a pluralsight subscription for a month so that I may fix it myself. 

As mentioned previously. This repo is effectively abandonware unless if I ever need it again or someone else takes over.

**Comment by vezaynk** [comment]
Is this still an issue?
