### ISSUE TITLE
Error: Protocol "blob:" not supported. 

### ISSUE THREAD

**Issue by Om4ar** [knyzorg/pluralsight-scraper#9]
scrapper return error `Error: Protocol "blob:" not supported. Expected "https:"`
and crash after

**Comment by vezaynk** [comment]
Can anybody confirm this issue?

**Comment by bahinapster** [comment]
Hello, 
I confirm the issue

**Comment by bahinapster** [comment]
quick fix, line 93
course.src = result.replace('blob:', '');

**Comment by bahinapster** [comment]
files are empty btw :/

**Comment by vezaynk** [comment]
> 
> course.src = result.replace('blob:', '');
> files are empty btw :/

As one would expect.
`blob://` is referring to some form of client-side storage, its not an actual url.

I was surprised it wasn't like this before, but it does significantly complicate matters now that it is.

**Comment by vezaynk** [comment]
This is now fixed with the new version.
